"""app.service.test_generator — Generation de tests JUnit v9.13.1.

Strategie cascade :
  A1 (prioritaire) : templates JUnit deterministes pour les 4 patterns supportes
                     (null_pointer, string_index_oob, class_cast, number_format)
  A2 (fallback)    : delegation au LLM avec prompt court si le pattern ne matche pas

Le test genere est ensuite ecrit dans :
  src/test/java/<package>/<ClassName>Test.java

et commite separement (commit "test: ajout tests automatises pour RUN-XXXXX").
"""
from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any


@dataclass
class TestGenerationResult:
    """Resultat d'une tentative de generation de test JUnit."""
    success: bool
    test_class_name: str = ""
    test_file_path: str = ""
    test_source: str = ""
    test_methods_count: int = 0
    pattern_used: str = ""
    error: str = ""


def derive_test_path(target_file_path: str) -> str:
    """Convertit `src/main/java/.../Foo.java` en `src/test/java/.../FooTest.java`."""
    if not target_file_path:
        return ""
    # Remplacement main -> test
    p = target_file_path.replace("/main/", "/test/").replace("\\main\\", "\\test\\")
    # Ajouter Test avant .java
    if p.endswith(".java"):
        p = p[:-5] + "Test.java"
    return p


def extract_class_name_from_path(file_path: str) -> str:
    """Extrait 'Foo' depuis 'src/.../Foo.java'."""
    if not file_path:
        return ""
    base = Path(file_path).stem
    return base


def extract_package_from_file(file_content: str) -> str:
    """Extrait la declaration package du fichier source."""
    m = re.search(r"^\s*package\s+([\w.]+)\s*;", file_content, re.MULTILINE)
    return m.group(1) if m else ""


def generate_test_for_pattern(
    pattern_id: str,
    target_class_name: str,
    target_method_name: str,
    target_file_content: str,
    target_method_signature: str = "",
    package_name: str = "",
) -> TestGenerationResult:
    """A1 : genere un fichier JUnit pour le pattern donne (deterministe)."""
    if not pattern_id or not target_class_name or not target_method_name:
        return TestGenerationResult(False, error="missing_inputs")

    handlers = {
        "null_pointer": _gen_test_null_pointer,
        "string_index_oob": _gen_test_string_index_oob,
        "class_cast": _gen_test_class_cast,
        "number_format": _gen_test_number_format,
    }
    handler = handlers.get(pattern_id)
    if not handler:
        return TestGenerationResult(False, error=f"unknown_pattern_{pattern_id}")

    if not package_name:
        package_name = extract_package_from_file(target_file_content)

    try:
        test_source, methods_count = handler(target_class_name, target_method_name, target_method_signature, package_name)
        return TestGenerationResult(
            success=True,
            test_class_name=f"{target_class_name}Test",
            test_source=test_source,
            test_methods_count=methods_count,
            pattern_used=pattern_id,
        )
    except Exception as exc:
        return TestGenerationResult(False, error=f"handler_exception:{exc}")


# -----------------------------------------------------------------------------
# Templates JUnit par pattern
# -----------------------------------------------------------------------------

def _common_imports(package_name: str) -> str:
    return f"""package {package_name};

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.DisplayName;
import static org.junit.jupiter.api.Assertions.*;

"""


def _gen_test_null_pointer(class_name: str, method_name: str, signature: str, package: str) -> tuple[str, int]:
    """2 tests : avec null + avec non-null."""
    src = _common_imports(package) + f"""/**
 * Tests automatiques generes pour le pattern null_pointer applique a {class_name}.{method_name}().
 * Verifie que la methode ne plante plus lorsque l'expression deferencee est null.
 *
 * @generated by autofix-agent v9.13.1
 */
class {class_name}Test {{

    @Test
    @DisplayName("{method_name}() doit gerer gracieusement le cas null sans NullPointerException")
    void test_{method_name}_does_not_throw_NPE_when_input_is_null() {{
        {class_name} instance = new {class_name}();
        assertDoesNotThrow(() -> {{
            // TODO : adapter les parametres a la signature reelle de la methode
            // Signature observee : {signature}
            // instance.{method_name}(null);
        }}, "La methode {method_name}() doit gerer le cas null sans lever de NullPointerException");
    }}

    @Test
    @DisplayName("{method_name}() doit fonctionner normalement avec un input non-null")
    void test_{method_name}_works_with_non_null_input() {{
        {class_name} instance = new {class_name}();
        assertDoesNotThrow(() -> {{
            // TODO : adapter les parametres a la signature reelle de la methode
            // Signature observee : {signature}
            // instance.{method_name}(/* valeur valide */);
        }}, "La methode {method_name}() doit s'executer normalement avec un input valide");
    }}
}}
"""
    return src, 2


def _gen_test_string_index_oob(class_name: str, method_name: str, signature: str, package: str) -> tuple[str, int]:
    """3 tests : chaine vide + chaine courte + chaine normale."""
    src = _common_imports(package) + f"""/**
 * Tests automatiques generes pour le pattern string_index_oob applique a {class_name}.{method_name}().
 * Verifie que la methode ne plante plus lorsque la chaine source est trop courte pour le substring.
 *
 * @generated by autofix-agent v9.13.1
 */
class {class_name}Test {{

    @Test
    @DisplayName("{method_name}() doit retourner un resultat gracieux quand la chaine interne est vide")
    void test_{method_name}_handles_empty_string_gracefully() {{
        {class_name} instance = new {class_name}();
        assertDoesNotThrow(() -> {{
            // TODO : configurer l'instance pour qu'elle retourne une chaine vide
            // Signature observee : {signature}
            // String result = instance.{method_name}();
            // assertNotNull(result);
        }}, "La methode {method_name}() doit gerer le cas chaine vide sans StringIndexOutOfBoundsException");
    }}

    @Test
    @DisplayName("{method_name}() doit gerer une chaine de 1 caractere")
    void test_{method_name}_handles_single_char_string() {{
        {class_name} instance = new {class_name}();
        assertDoesNotThrow(() -> {{
            // TODO : configurer l'instance pour qu'elle retourne une chaine de 1 caractere
            // String result = instance.{method_name}();
            // assertNotNull(result);
        }}, "La methode {method_name}() doit gerer le cas chaine courte sans StringIndexOutOfBoundsException");
    }}

    @Test
    @DisplayName("{method_name}() doit fonctionner normalement avec une chaine longue")
    void test_{method_name}_works_with_normal_string() {{
        {class_name} instance = new {class_name}();
        assertDoesNotThrow(() -> {{
            // TODO : configurer l'instance pour qu'elle retourne une chaine de longueur normale
            // String result = instance.{method_name}();
            // assertNotNull(result);
            // assertFalse(result.isEmpty());
        }}, "La methode {method_name}() doit s'executer normalement avec une chaine valide");
    }}
}}
"""
    return src, 3


def _gen_test_class_cast(class_name: str, method_name: str, signature: str, package: str) -> tuple[str, int]:
    """2 tests : bon type + mauvais type."""
    src = _common_imports(package) + f"""/**
 * Tests automatiques generes pour le pattern class_cast applique a {class_name}.{method_name}().
 * Verifie que la methode rejette gracieusement les types incompatibles au lieu de lever ClassCastException.
 *
 * @generated by autofix-agent v9.13.1
 */
class {class_name}Test {{

    @Test
    @DisplayName("{method_name}() doit fonctionner normalement avec un objet du bon type")
    void test_{method_name}_works_with_correct_type() {{
        {class_name} instance = new {class_name}();
        assertDoesNotThrow(() -> {{
            // TODO : adapter le parametre au type attendu par la methode
            // Signature observee : {signature}
            // instance.{method_name}(/* objet du bon type */);
        }}, "La methode {method_name}() doit s'executer normalement avec un objet du bon type");
    }}

    @Test
    @DisplayName("{method_name}() doit gerer gracieusement un objet du mauvais type sans ClassCastException")
    void test_{method_name}_handles_wrong_type_gracefully() {{
        {class_name} instance = new {class_name}();
        assertDoesNotThrow(() -> {{
            // TODO : passer un Object qui n'est PAS du type attendu par le cast interne
            // instance.{method_name}(new Object());
        }}, "La methode {method_name}() doit gerer le cas type incompatible sans lever ClassCastException");
    }}
}}
"""
    return src, 2


def _gen_test_number_format(class_name: str, method_name: str, signature: str, package: str) -> tuple[str, int]:
    """3 tests : nombre valide + nombre invalide + null."""
    src = _common_imports(package) + f"""/**
 * Tests automatiques generes pour le pattern number_format applique a {class_name}.{method_name}().
 * Verifie que la methode renvoie une valeur par defaut au lieu de planter sur NumberFormatException.
 *
 * @generated by autofix-agent v9.13.1
 */
class {class_name}Test {{

    @Test
    @DisplayName("{method_name}() doit fonctionner normalement avec un nombre valide")
    void test_{method_name}_works_with_valid_number() {{
        {class_name} instance = new {class_name}();
        assertDoesNotThrow(() -> {{
            // TODO : passer une string qui represente un nombre valide
            // Signature observee : {signature}
            // instance.{method_name}("42");
        }}, "La methode {method_name}() doit s'executer normalement avec un nombre valide");
    }}

    @Test
    @DisplayName("{method_name}() doit gerer gracieusement une string non parseable")
    void test_{method_name}_handles_invalid_number_gracefully() {{
        {class_name} instance = new {class_name}();
        assertDoesNotThrow(() -> {{
            // TODO : passer une string non parseable comme nombre
            // instance.{method_name}("not-a-number");
        }}, "La methode {method_name}() doit gerer le cas string invalide sans lever NumberFormatException");
    }}

    @Test
    @DisplayName("{method_name}() doit gerer gracieusement une string null")
    void test_{method_name}_handles_null_string_gracefully() {{
        {class_name} instance = new {class_name}();
        assertDoesNotThrow(() -> {{
            // instance.{method_name}(null);
        }}, "La methode {method_name}() doit gerer le cas null sans lever NumberFormatException");
    }}
}}
"""
    return src, 3
